### ISSUE TITLE
Notification overload bug

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/Grow-IoT#433] opened 2017-12-08 23:10 UTC
Getting tons of notifications as "Alert: undefined undefined" which I take to be coming from a disconnected sensor probe, just maybe.

The sheer quantity of notifications seems to have slowed down the UI significantly. #404 is related here.

**Comment by JakeHartnell** [comment] 2017-12-27 21:34
Note, we need to flesh this issue out a bit more. I attempted to look into it, but I can't reproduce.

**Comment by JakeHartnell** [comment] 2018-01-02 21:19
Closing until we figure out how to reproduce this.

**Closed as completed by JakeHartnell** 2018-01-02 21:19 UTC
Labels: bug
